INSERT IGNORE INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `metadata`, `desc`, `weight`) VALUES 
('show_ticket_bigband_a', 'Bigband A', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a theater show in Saint Denis', 0.1),
('show_ticket_bigband_b', 'Bigband B', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a theater show in Saint Denis', 0.1),
('show_ticket_bulletcatch', 'Bullet Catch', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a theater show in Saint Denis', 0.1),
('show_ticket_cancan_a', 'Cancan A', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a theater show in Saint Denis', 0.1),
('show_ticket_cancan_b', 'Cancan B', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a theater show in Saint Denis', 0.1),
('show_ticket_escapeartist', 'Escape Artist', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a theater show in Saint Denis', 0.1),
('show_ticket_escapenoose', 'Noose Escape', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a theater show in Saint Denis', 0.1),
('show_ticket_firebreath', 'Fire Breather', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a theater show in Saint Denis', 0.1),
('show_ticket_firedance_a', 'Fire Dance A', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a theater show in Saint Denis', 0.1),
('show_ticket_firedance_b', 'Fire Dance B', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a theater show in Saint Denis', 0.1),
('show_ticket_flexfight', 'Flex Fight', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a theater show in Saint Denis', 0.1),
('show_ticket_oddfellows', 'Oddfellows', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a theater show in Saint Denis', 0.1),
('show_ticket_snakedance_a', 'Snake Dance A', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a theater show in Saint Denis', 0.1),
('show_ticket_snakedance_b', 'Snake Dance B', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a theater show in Saint Denis', 0.1),
('show_ticket_strongwoman', 'Strongwoman', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a theater show in Saint Denis', 0.1),
('show_ticket_sworddance', 'Sword Dance', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a theater show in Saint Denis', 0.1),
('movie_disc_bear_saintdenis', 'The Bear', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a movie in Saint Denis', 0.1),
('movie_disc_josiah_saintdenis', 'Josiah', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a movie in Saint Denis', 0.1),
('movie_disc_flight_saintdenis', 'Human Flight', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a movie in Saint Denis', 0.1),
('movie_disc_saviors_saintdenis', 'Saviors and Savages', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a movie in Saint Denis', 0.1),
('movie_disc_ghoststory_saintdenis', 'Ghost Story', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a movie in Saint Denis', 0.1),
('movie_disc_damnation_saintdenis', 'Damnation by Direct Current', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a movie in Saint Denis', 0.1),
('movie_disc_farmersdaughter_saintdenis', 'The Farmer Daughter', 200, 1, 'item_standard', 1,'{}', 'Ticket to see a movie in Saint Denis', 0.1),
('movie_disc_modernmedicine_saintdenis', 'Modern Medicine', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Saint Denis', 0.1),
('movie_disc_strongestman_saintdenis', 'The Strongest Man', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Saint Denis', 0.1),
('movie_disc_sweetheart_saintdenis', 'Sketching for the Sweetheart', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Saint Denis', 0.1),
('movie_disc_beartent_saintdenis', 'The Bear 2', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Saint Denis', 0.1),
('movie_disc_josiahtent_saintdenis', 'Josiah 2', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Saint Denis', 0.1),
('movie_disc_flighttent_saintdenis', 'Human Flight 2', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Saint Denis', 0.1),
('movie_disc_saviorstent_saintdenis', 'Saviors and Savages 2', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Saint Denis', 0.1),
('movie_disc_ghoststorytent_saintdenis', 'Ghost Story 2', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Saint Denis', 0.1),
('movie_disc_bear_blackwater', 'The Bear', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Blackwater', 0.1),
('movie_disc_josiah_blackwater', 'Josiah', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Blackwater', 0.1),
('movie_disc_flight_blackwater', 'Human Flight', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Blackwater', 0.1),
('movie_disc_saviors_blackwater', 'Saviors and Savages', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Blackwater', 0.1),
('movie_disc_ghoststory_blackwater', 'Ghost Story', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Blackwater', 0.1),
('movie_disc_damnation_blackwater', 'Downstream Damnation', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Blackwater', 0.1),
('movie_disc_farmersdaughter_blackwater', 'The Farmer Daughter', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Blackwater', 0.1),
('movie_disc_modernmedicine_blackwater', 'Modern Medicine', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Blackwater', 0.1),
('movie_disc_strongestman_blackwater', 'The Strongest Man', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Blackwater', 0.1),
('movie_disc_sweetheart_blackwater', 'Sketching for my Sweetheart', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Blackwater', 0.1),
('movie_disc_beartent_blackwater', 'The Bear 2', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Blackwater', 0.1),
('movie_disc_josiahtent_blackwater', 'Josiah 2', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Blackwater', 0.1),
('movie_disc_flighttent_blackwater', 'Human Flight 2', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Blackwater', 0.1),
('movie_disc_saviorstent_blackwater', 'Saviors and Savages 2', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Blackwater', 0.1),
('movie_disc_ghoststorytent_blackwater', 'Ghost Story 2', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Blackwater', 0.1),
('movie_disc_bear_valentine', 'The Bear', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Valentine', 0.1),
('movie_disc_josiah_valentine', 'Josiah', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Valentine', 0.1),
('movie_disc_flight_valentine', 'Human Flight', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Valentine', 0.1),
('movie_disc_saviors_valentine', 'Saviors and Savages', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Valentine', 0.1),
('movie_disc_ghoststory_valentine', 'Ghost Story', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Valentine', 0.1),
('movie_disc_damnation_valentine', 'Downstream Damnation', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Valentine', 0.1),
('movie_disc_farmersdaughter_valentine', 'The Farmer Daughter', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Valentine', 0.1),
('movie_disc_modernmedicine_valentine', 'Modern Medicine', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Valentine', 0.1),
('movie_disc_strongestman_valentine', 'The Strongest Man', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Valentine', 0.1),
('movie_disc_sweetheart_valentine', 'Sketching for my Sweetheart', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Valentine', 0.1),
('movie_disc_beartent_valentine', 'The Bear 2', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Valentine', 0.1),
('movie_disc_josiahtent_valentine', 'Josiah 2', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Valentine', 0.1),
('movie_disc_flighttent_valentine', 'Human Flight 2', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Valentine', 0.1),
('movie_disc_saviorstent_valentine', 'Saviors and Savages 2', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Valentine', 0.1),
('movie_disc_ghoststorytent_valentine', 'Ghost Story 2', 200, 1, 'item_standard', 1,'{}', 'Ticket to watch a movie in Valentine', 0.1);
